### ISSUE TITLE
[Bug]: Staging "Forgot Password" flow fails to submit form

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1295]
## Description

I am unable to submit a "reset my password" request on Staging

## Steps to reproduce

1. Navigate to the "Log In" page
2. Click "Forgot my password"
3. Fill in your email and click submit on the form.
4. Get told of an "Application Error"

## What you expected to happen

I should be sent an email with a link to reset my password

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/173814809-c4bedcd8-af3c-4864-bfa2-ade4563a5933.png)

**Comment by katjam** [comment]
Email does come through but got the error when I submitted.

**Comment by ivankocienski** [comment]
production log
```
2022-06-15T11:23:43.573061918Z app[web.1]: I, [2022-06-15T11:23:43.572898 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Started POST "/users/password" for 92.239.153.49 at 2022-06-15 11:23:43 +0000
2022-06-15T11:23:43.584494232Z app[web.1]: I, [2022-06-15T11:23:43.584330 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Processing by Users::PasswordsController#create as TURBO_STREAM
2022-06-15T11:23:43.585273052Z app[web.1]: I, [2022-06-15T11:23:43.585124 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   Parameters: {"authenticity_token"=>"rYLyaRK6L86C-4Xr3qx7lLA79Hycdt5vaRaAfDQnepahvPzUXCrhXxKxT0j1sKUop9H7z_p6SJ75Yv1D2nxYqA", "user"=>{"email"=>"katja@gfsc.studio"}, "commit"=>"Send me reset password instructions"}
2022-06-15T11:23:43.599939926Z app[web.1]: D, [2022-06-15T11:23:43.599756 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   Site Load (0.5ms)  SELECT "sites".* FROM "sites" WHERE "sites"."domain" = $1 LIMIT $2  [["domain", "placecal.org"], ["LIMIT", 1]]
2022-06-15T11:23:43.623082118Z app[web.1]: D, [2022-06-15T11:23:43.622941 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   User Load (7.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "katja@gfsc.studio"], ["LIMIT", 1]]
2022-06-15T11:23:43.635917383Z app[web.1]: D, [2022-06-15T11:23:43.635764 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   User Load (4.0ms)  SELECT "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["reset_password_token", "0478b2e2605a2a85256baab4586d2fc1d9db5c9082989d93f07d02f175e325cc"], ["LIMIT", 1]]
2022-06-15T11:23:43.686992818Z app[web.1]: D, [2022-06-15T11:23:43.686836 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   TRANSACTION (0.6ms)  BEGIN
2022-06-15T11:23:43.694657119Z app[web.1]: D, [2022-06-15T11:23:43.694504 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   User Update (5.0ms)  UPDATE "users" SET "reset_password_token" = $1, "reset_password_sent_at" = $2, "updated_at" = $3 WHERE "users"."id" = $4  [["reset_password_token", "0478b2e2605a2a85256baab4586d2fc1d9db5c9082989d93f07d02f175e325cc"], ["reset_password_sent_at", "2022-06-15 11:23:43.643752"], ["updated_at", "2022-06-15 11:23:43.660554"], ["id", 59]]
2022-06-15T11:23:43.710137641Z app[web.1]: D, [2022-06-15T11:23:43.709880 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   TRANSACTION (1.4ms)  COMMIT
2022-06-15T11:23:43.790907697Z app[web.1]: D, [2022-06-15T11:23:43.790719 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   Rendering devise/mailer/reset_password_instructions.html.erb
2022-06-15T11:23:43.794854871Z app[web.1]: I, [2022-06-15T11:23:43.794681 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]   Rendered devise/mailer/reset_password_instructions.html.erb (Duration: 3.2ms | Allocations: 79)
2022-06-15T11:23:43.840066275Z app[web.1]: D, [2022-06-15T11:23:43.839849 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Devise::Mailer#reset_password_instructions: processed outbound mail in 84.5ms
2022-06-15T11:23:44.490357422Z app[web.1]: I, [2022-06-15T11:23:44.490144 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Delivered mail 62a9c13fd777b_d160804529e@2888bea73500.mail (648.2ms)
2022-06-15T11:23:44.491143420Z app[web.1]: D, [2022-06-15T11:23:44.491004 #13] DEBUG -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Date: Wed, 15 Jun 2022 11:23:43 +0000
2022-06-15T11:23:44.491235231Z app[web.1]: From: support@placecal.org
2022-06-15T11:23:44.491317187Z app[web.1]: Reply-To: support@placecal.org
2022-06-15T11:23:44.491341280Z app[web.1]: To: katja@gfsc.studio
2022-06-15T11:23:44.491806117Z app[web.1]: Message-ID: <62a9c13fd777b_d160804529e@2888bea73500.mail>
2022-06-15T11:23:44.491838594Z app[web.1]: Subject: Reset password instructions
2022-06-15T11:23:44.491875437Z app[web.1]: Mime-Version: 1.0
2022-06-15T11:23:44.491885573Z app[web.1]: Content-Type: text/html;
2022-06-15T11:23:44.491935830Z app[web.1]:  charset=UTF-8
2022-06-15T11:23:44.491947757Z app[web.1]: Content-Transfer-Encoding: 7bit
2022-06-15T11:23:44.491975649Z app[web.1]:
2022-06-15T11:23:44.491986111Z app[web.1]: <p>Hello katja@gfsc.studio!</p>
2022-06-15T11:23:44.492026590Z app[web.1]:
2022-06-15T11:23:44.492037239Z app[web.1]: <p>Someone has requested a link to change your password. You can do this through the link below.</p>
2022-06-15T11:23:44.492065884Z app[web.1]:
2022-06-15T11:23:44.492974360Z app[web.1]: <p><a href="https://placecal.org/users/password/edit?reset_password_token=2pNscSMfbrVQptAYP2S-">Change my password</a></p>
2022-06-15T11:23:44.493000306Z app[web.1]:
2022-06-15T11:23:44.493075375Z app[web.1]: <p>If you didn't request this, please ignore this email.</p>
2022-06-15T11:23:44.493098843Z app[web.1]: <p>Your password won't change until you access the link above and create a new one.</p>
2022-06-15T11:23:44.493129400Z app[web.1]:
2022-06-15T11:23:44.503156668Z app[web.1]: I, [2022-06-15T11:23:44.502959 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Redirected to
2022-06-15T11:23:44.507639575Z app[web.1]: I, [2022-06-15T11:23:44.507424 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] Completed 500 Internal Server Error in 920ms (ActiveRecord: 18.7ms | Allocations: 5539)
2022-06-15T11:23:44.760122740Z app[web.1]: I, [2022-06-15T11:23:44.759916 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] [Rollbar] Scheduling item
2022-06-15T11:23:44.760816547Z app[web.1]: I, [2022-06-15T11:23:44.760662 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] [Rollbar] Sending item
2022-06-15T11:23:44.777088823Z app[web.1]: I, [2022-06-15T11:23:44.776866 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] [Rollbar] Sending json
2022-06-15T11:23:44.919591394Z app[web.1]: W, [2022-06-15T11:23:44.919360 #13]  WARN -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] [Rollbar] Got unexpected status code from Rollbar api: 429
2022-06-15T11:23:44.920810989Z app[web.1]: I, [2022-06-15T11:23:44.920111 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] [Rollbar] Response: {
2022-06-15T11:23:44.920865645Z app[web.1]:   "err": 1,
2022-06-15T11:23:44.920947451Z app[web.1]:   "message": "Over plan monthly limit and overages disabled. Project id 526493 access token e7b45234335d462e99a850743b1d01f3."
2022-06-15T11:23:44.920964152Z app[web.1]: }
2022-06-15T11:23:44.921908303Z app[web.1]: I, [2022-06-15T11:23:44.921414 #13]  INFO -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8] [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=f7e9f921-2a66-4e61-a92e-7f0c068fdac4 (only available if report was successful)
2022-06-15T11:23:44.927886817Z app[web.1]: F, [2022-06-15T11:23:44.924801 #13] FATAL -- : [324af5a6-cd2a-4c80-bf13-11a94013e1a8]
2022-06-15T11:23:44.927955205Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] ArgumentError (Nil location provided. Can't build URI.):
2022-06-15T11:23:44.929565662Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8]
2022-06-15T11:23:44.929628534Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/polymorphic_routes.rb:212:in `polymorphic_method'
2022-06-15T11:23:44.929675211Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/polymorphic_routes.rb:116:in `polymorphic_url'
2022-06-15T11:23:44.929686070Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/url_for.rb:188:in `full_url_for'
2022-06-15T11:23:44.929721940Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/url_for.rb:171:in `url_for'
2022-06-15T11:23:44.929746116Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/redirecting.rb:110:in `_compute_redirect_to_location'
2022-06-15T11:23:44.929778629Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/redirecting.rb:63:in `redirect_to'
2022-06-15T11:23:44.929799309Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/flash.rb:58:in `redirect_to'
2022-06-15T11:23:44.930551374Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:66:in `block in redirect_to'
2022-06-15T11:23:44.930592446Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `block in instrument'
2022-06-15T11:23:44.931765170Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-06-15T11:23:44.931788666Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `instrument'
2022-06-15T11:23:44.931842315Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:65:in `redirect_to'
2022-06-15T11:23:44.931854072Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/responder.rb:147:in `redirect_to'
2022-06-15T11:23:44.931893614Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/responder.rb:207:in `navigation_behavior'
2022-06-15T11:23:44.931906930Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/responder.rb:174:in `rescue in to_html'
2022-06-15T11:23:44.931948179Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/responder.rb:171:in `to_html'
2022-06-15T11:23:44.932347112Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/responder.rb:165:in `respond'
2022-06-15T11:23:44.933318541Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/responder.rb:158:in `call'
2022-06-15T11:23:44.933337449Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] responders (3.0.1) lib/action_controller/respond_with.rb:213:in `respond_with'
2022-06-15T11:23:44.933341247Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] devise (4.8.1) app/controllers/devise/passwords_controller.rb:19:in `create'
2022-06-15T11:23:44.933344230Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
2022-06-15T11:23:44.933347316Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/abstract_controller/base.rb:228:in `process_action'
2022-06-15T11:23:44.933350264Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
2022-06-15T11:23:44.933353239Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
2022-06-15T11:23:44.933356140Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
2022-06-15T11:23:44.933359124Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actiontext (6.1.6) lib/action_text/rendering.rb:20:in `with_renderer'
2022-06-15T11:23:44.933361976Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actiontext (6.1.6) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
2022-06-15T11:23:44.933365315Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `instance_exec'
2022-06-15T11:23:44.933368238Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2022-06-15T11:23:44.933378552Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/callbacks.rb:137:in `run_callbacks'
2022-06-15T11:23:44.933381591Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
2022-06-15T11:23:44.933385943Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
2022-06-15T11:23:44.933388996Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
2022-06-15T11:23:44.933483305Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `block in instrument'
2022-06-15T11:23:44.933488214Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-06-15T11:23:44.933491223Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/notifications.rb:203:in `instrument'
2022-06-15T11:23:44.933494211Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
2022-06-15T11:23:44.933497182Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
2022-06-15T11:23:44.933500101Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activerecord (6.1.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
2022-06-15T11:23:44.933503020Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/abstract_controller/base.rb:165:in `process'
2022-06-15T11:23:44.933506012Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionview (6.1.6) lib/action_view/rendering.rb:39:in `process'
2022-06-15T11:23:44.933508905Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal.rb:190:in `dispatch'
2022-06-15T11:23:44.933514008Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_controller/metal.rb:254:in `dispatch'
2022-06-15T11:23:44.933517026Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
2022-06-15T11:23:44.933519879Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
2022-06-15T11:23:44.933522827Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
2022-06-15T11:23:44.933525939Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/mapper.rb:49:in `serve'
2022-06-15T11:23:44.933528817Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
2022-06-15T11:23:44.933531777Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `each'
2022-06-15T11:23:44.933543170Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/journey/router.rb:32:in `serve'
2022-06-15T11:23:44.933546716Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
2022-06-15T11:23:44.933553253Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
2022-06-15T11:23:44.933556168Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
2022-06-15T11:23:44.933559067Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] omniauth (2.1.0) lib/omniauth/builder.rb:44:in `call'
2022-06-15T11:23:44.933561889Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
2022-06-15T11:23:44.933564773Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
2022-06-15T11:23:44.933567914Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] warden (1.2.9) lib/warden/manager.rb:34:in `call'
2022-06-15T11:23:44.933570711Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
2022-06-15T11:23:44.933573633Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
2022-06-15T11:23:44.933576460Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/conditional_get.rb:40:in `call'
2022-06-15T11:23:44.933579378Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/head.rb:12:in `call'
2022-06-15T11:23:44.933582184Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
2022-06-15T11:23:44.933585057Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
2022-06-15T11:23:44.933601968Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
2022-06-15T11:23:44.933606822Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
2022-06-15T11:23:44.933610057Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
2022-06-15T11:23:44.933612912Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2022-06-15T11:23:44.933615823Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
2022-06-15T11:23:44.933618837Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2022-06-15T11:23:44.933622225Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
2022-06-15T11:23:44.933625106Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rollbar (3.3.0) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
2022-06-15T11:23:44.933628078Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rollbar (3.3.0) lib/rollbar.rb:145:in `scoped'
2022-06-15T11:23:44.933631138Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rollbar (3.3.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
2022-06-15T11:23:44.933634080Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
2022-06-15T11:23:44.933641470Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rollbar (3.3.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
2022-06-15T11:23:44.933644473Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2022-06-15T11:23:44.933647466Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] railties (6.1.6) lib/rails/rack/logger.rb:37:in `call_app'
2022-06-15T11:23:44.933650430Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] railties (6.1.6) lib/rails/rack/logger.rb:26:in `block in call'
2022-06-15T11:23:44.933653399Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
2022-06-15T11:23:44.933661068Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/tagged_logging.rb:37:in `tagged'
2022-06-15T11:23:44.933664085Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `tagged'
2022-06-15T11:23:44.933666999Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] railties (6.1.6) lib/rails/rack/logger.rb:26:in `call'
2022-06-15T11:23:44.933670153Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2022-06-15T11:23:44.933673037Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
2022-06-15T11:23:44.933676009Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
2022-06-15T11:23:44.933678999Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
2022-06-15T11:23:44.933681874Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
2022-06-15T11:23:44.933685398Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] activesupport (6.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2022-06-15T11:23:44.933688386Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
2022-06-15T11:23:44.933691393Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/static.rb:24:in `call'
2022-06-15T11:23:44.933694339Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
2022-06-15T11:23:44.933697175Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] actionpack (6.1.6) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
2022-06-15T11:23:44.933700053Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
2022-06-15T11:23:44.933702865Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] railties (6.1.6) lib/rails/engine.rb:539:in `call'
2022-06-15T11:23:44.933705681Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] puma (5.6.4) lib/puma/configuration.rb:252:in `call'
2022-06-15T11:23:44.933708497Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
2022-06-15T11:23:44.933711351Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
2022-06-15T11:23:44.933716827Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
2022-06-15T11:23:44.933743127Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] puma (5.6.4) lib/puma/server.rb:441:in `process_client'
2022-06-15T11:23:44.933747393Z app[web.1]: [324af5a6-cd2a-4c80-bf13-11a94013e1a8] puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'


```
