### ISSUE TITLE
[Bug]: EventBrite calendars are stuck in `in_worker` state

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1539]
## Description

'Eventbrite'
'FTM London Eventbrite'
'London LGBTQ+ Community Centre Eventbrite'
'RAH! Eventbrite Feed'
'Bavs Eventbrite feed'
'LGBT Hero'

This is a non-exhaustive list

Problem is the way Addresses validate postcodes

```
[ActiveJob] [CalendarImporterJob] [87b3bbde-bc16-4405-a9a2-f226fb108987] Error performing CalendarImporterJob (Job ID: 87b3bbde-bc16-4405-a9a2-f226fb108987) from DelayedJob(default) in 5002.54ms: NoMethodError (undefined method `strip' for nil:NilClass):
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/giro_postcode.rb:21:in `parse'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/parser_chain.rb:9:in `block in parse'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/parser_chain.rb:8:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/parser_chain.rb:8:in `parse'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode.rb:17:in `parse'
/app/app/models/address.rb:101:in `search'
/app/app/jobs/calendar_importer/event_resolver.rb:88:in `event_strategy'
/app/app/jobs/calendar_importer/event_resolver.rb:62:in `call'
/app/app/jobs/calendar_importer/event_resolver.rb:62:in `determine_location_for_strategy'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:69:in `process_event'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:24:in `block in run'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:23:in `each'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:23:in `run'
/app/app/jobs/calendar_importer_job.rb:47:in `perform'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/execution.rb:48:in `block in perform_now'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/i18n-1.12.0/lib/i18n.rb:317:in `with_locale'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:21:in `block in instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:31:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/logging.rb:22:in `block in tag_logger'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:37:in `tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in `tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/logging.rb:22:in `tag_logger'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/execution.rb:47:in `perform_now'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.6.1/lib/active_job/execution.rb:18:in `perform_now'
/app/lib/tasks/events.rake:65:in `block (3 levels) in <main>'
/app/lib/tasks/events.rake:60:in `each'
/app/lib/tasks/events.rake:60:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/command.rb:50:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/bin/rails:4:in `<main>'

NoMethodError: bad thing: undefined method `strip' for nil:NilClass
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/giro_postcode.rb:21:in `parse'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/parser_chain.rb:9:in `block in parse'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/parser_chain.rb:8:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode/parser_chain.rb:8:in `parse'
/app/vendor/bundle/ruby/2.7.0/gems/uk_postcode-2.1.8/lib/uk_postcode.rb:17:in `parse'
/app/app/models/address.rb:101:in `search'
```

**Comment by aaaaargZombies** [comment]
This was flagged on Discord by GI person so update them when dealt with
