### ISSUE TITLE
[Bug]: LGBT Hero has no events

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1614]
## Description

https://trans-dimension.placecal.org/partners/lgbt-hero

no event's showing on placecal but it has events at https://www.eventbrite.co.uk/o/lgbt-hero-17463624603

In placecal admin it looks like the calendar is stuck `in_worker`

## Steps to reproduce

visit placecal partner page. Still investigating root of issue.

## What you expected to happen

placecal events should match eventbrite events

**Comment by aaaaargZombies** [comment]
possibly related to #1541

**Comment by aaaaargZombies** [comment]
ran `rake import:events_from_source[108]` locally and I now have events on my machine!?

**Comment by aaaaargZombies** [comment]
similar issue with other eventbrite calendars - attempt to use rake to import from RAH https://admin.placecal-staging.org/calendars/76/edit

```sh
root@placecal-staging:~# dokku run placecal rake import:events_from_source[108]
I, [2022-12-13T13:29:39.608575 #12]  INFO -- : [ActiveJob] [CalendarImporterJob] [ed4529c5-28f4-42d5-ad58-ef8dd5e76f21] Performing CalendarImporterJob (Job ID: ed4529c5-28f4-42d5-ad58-ef8dd5e76f21) from DelayedJob(default) enqueued at  with arguments: "108", Tue, 13 Dec 2022 00:00:00.000000000 GMT +00:00, true
D, [2022-12-13T13:29:39.772497 #12] DEBUG -- : [ActiveJob] [CalendarImporterJob] [ed4529c5-28f4-42d5-ad58-ef8dd5e76f21]   Calendar Load (0.8ms)  SELECT "calendars".* FROM "calendars" WHERE "calendars"."id" = $1 LIMIT $2  [["id", 108], ["LIMIT", 1]]
Importing events for calendar jonny 2 (ID 108)D, [2022-12-13T13:29:39.879955 #12] DEBUG -- : [ActiveJob] [CalendarImporterJob] [ed4529c5-28f4-42d5-ad58-ef8dd5e76f21]   Partner Load (1.2ms)  SELECT "partners".* FROM "partners" WHERE "partners"."id" = $1 LIMIT $2  [["id", 54], ["LIMIT", 1]]
 for place Manchester Museum (ID 54) is forced
E, [2022-12-13T13:29:39.988968 #12] ERROR -- : [ActiveJob] [CalendarImporterJob] [ed4529c5-28f4-42d5-ad58-ef8dd5e76f21] Error performing CalendarImporterJob (Job ID: ed4529c5-28f4-42d5-ad58-ef8dd5e76f21) from DelayedJob(default) in 379.16ms: CalendarImporter::CalendarImporter::InaccessibleFeed (The URL could not be reached for calendar jonny 2):
/app/app/jobs/calendar_importer/calendar_importer.rb:44:in `validate_feed!'
/app/app/jobs/calendar_importer/calendar_importer.rb:24:in `initialize'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:44:in `new'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:44:in `parser'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:48:in `calendar_source'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:58:in `event_data_from_parser'
/app/app/jobs/calendar_importer/calendar_importer_task.rb:15:in `run'
/app/app/jobs/calendar_importer_job.rb:47:in `perform'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/execution.rb:48:in `block in perform_now'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/i18n-1.12.0/lib/i18n.rb:317:in `with_locale'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:21:in `block in instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:31:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/logging.rb:22:in `block in tag_logger'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:37:in `tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/logging.rb:22:in `tag_logger'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/execution.rb:47:in `perform_now'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.7/lib/active_job/execution.rb:18:in `perform_now'
/app/lib/tasks/events.rake:65:in `block (3 levels) in <main>'
/app/lib/tasks/events.rake:60:in `each'
/app/lib/tasks/events.rake:60:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/app/bin/rake:6:in `<main>'
D, [2022-12-13T13:29:39.996901 #12] DEBUG -- :   Calendar Load (1.3ms)  SELECT "calendars".* FROM "calendars" WHERE "calendars"."id" = $1 LIMIT $2  [["id", 108], ["LIMIT", 1]]
```

**Comment by aaaaargZombies** [comment]
running the following on staging

```sh
root@placecal-staging:~# dokku run placecal rake import:events_from_source[76]
```
seems to have pulled [RAH! Eventbrite Feed](https://admin.placecal-staging.org/calendars/76/edit) out of `in_worker` and added some events to the calendar though it reports a long list of events that could not be listed.

> ### Important Notices
> 
> The following events could not be imported due to invalid data:
> 
> - Girlfriend in a Coma film screening No place or address could be created or found for the event location: MMU Business School
> - ONLINE EVENT: Professor Sylvester Arnab - ‘Empathic and Experiential Gameful and Playful design practices’ No place or address could be created or found for the event location:
> - ONLINE EVENT: Digital Politics No place or address could be created or found for the event location:
> - Crafting Futures the Tai Lue Project - LAUNCH No place or address could be created or found for the event location:
> - Melmoth’s Afterlives, Book Group 1: Charles Maturin’s Melmoth the Wanderer No place or address could be created or 
>
> [...]
>
> - Neoliberal Irish Gothic: The Death and Afterlife of the Celtic Tiger No place or address could be created or found for the event location:
> - Living in the Upside Down: The Retro 1980s No place or address could be created or found for the event location:
> - Gothic Cinema: Towards a Definition No place or address could be created or found for the event location:
> - AMBITION, MYSTERY AND ROMANCE: CAN YOU PLAY THE GAME? No place or address could be created or found for the event location:

**Comment by aaaaargZombies** [comment]
I ran the rake task on production for LGDBT Hero and it seems to have cleared the error state and setting the calendar to queue for import form the admin UI works as expected.

I'm going to close this and look for other eventbrite calendars that might need freeing from their `in_worker` state.
