### ISSUE TITLE
Create new site skips validations and throws a 501 without name, slug, domain

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#896]
**Describe the bug**

**To Reproduce**
1. Go to http://admin.lvh.me:3000/sites/new
2. Click on 'Create site'
3. See error below

**Suggested tests**

- [ ] Create site cannot progress without validation fields filled in
- [ ] Create new site with primary neighbourhood only saves. Ditto for edit/update
- [ ] Create new site with both primary and secondary neighbourhood saves. Ditto for edit/update.
- [ ] Create new site with primary neighbourhood == secondary neighbourhood just saves the primary neighbourhood. Ditto for edit/update
- [ ] Same as above but with a few secondary neighbourhoods
- [ ] Primary neighbourhood is mandatory (might exist already)

```
Started POST "/sites" for 127.0.0.1 at 2022-02-01 17:21:06 +0000
Processing by Admin::SitesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"izx1Ph11riDGB6/IPF4NSUFluHdU6nM0Y5VEV/IqFaU+FEn+cucT7OTC3sLQY5MYBlWJYWcoq4qatUTRKAEi2Q==", "site"=>{"name"=>"", "place_name"=>"", "tagline"=>"The Community Calendar", "domain"=>"", "slug"=>"", "description"=>"", "is_published"=>"0", "site_admin_id"=>"", "theme"=>"pink", "hero_image_credit"=>"", "sites_neighbourhood_attributes"=>{"relation_type"=>"Primary", "neighbourhood_id"=>"9761"}}, "commit"=>"Create Site", "subdomain"=>"admin"}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  TRANSACTION (0.1ms)  BEGIN
  ↳ app/controllers/admin/sites_controller.rb:28:in `create'
  Neighbourhood Load (0.2ms)  SELECT "neighbourhoods".* FROM "neighbourhoods" WHERE "neighbourhoods"."id" = $1 LIMIT $2  [["id", 9761], ["LIMIT", 1]]
  ↳ app/controllers/admin/sites_controller.rb:28:in `create'
  SitesNeighbourhood Exists? (0.2ms)  SELECT 1 AS one FROM "sites_neighbourhoods" WHERE "sites_neighbourhoods"."neighbourhood_id" = $1 AND "sites_neighbourhoods"."site_id" IS NULL LIMIT $2  [["neighbourhood_id", 9761], ["LIMIT", 1]]
  ↳ app/controllers/admin/sites_controller.rb:28:in `create'
  TRANSACTION (0.1ms)  ROLLBACK
  ↳ app/controllers/admin/sites_controller.rb:28:in `create'
  Rendering layout layouts/admin/application.html.erb
  Rendering admin/sites/new.html.erb within layouts/admin/application
  Rendered app/components/error/_error.html.erb (Duration: 1.5ms | Allocations: 1294)
  User Load (0.5ms)  SELECT "users".* FROM "users"
  ↳ app/views/admin/sites/_form.html.erb:18
  Rendered admin/sites/_form.html.erb (Duration: 41.1ms | Allocations: 41633)
  Rendered app/components/admin_new/_admin_new.html.erb (Duration: 41.3ms | Allocations: 41717)
  Rendered admin/sites/new.html.erb within layouts/admin/application (Duration: 43.0ms | Allocations: 43668)
  Rendered layout layouts/admin/application.html.erb (Duration: 43.1ms | Allocations: 43733)
Completed 500 Internal Server Error in 56ms (ActiveRecord: 1.5ms | Allocations: 52643)



NoMethodError - undefined method `filter' for nil:NilClass:
  app/helpers/sites_helper.rb:6:in `options_for_sites_neighbourhoods'
  app/views/admin/sites/_form.html.erb:61
  app/views/admin/sites/_form.html.erb:54
  app/views/admin/sites/_form.html.erb:1
  app/components/admin_new/_admin_new.html.erb:5
  app/views/admin/sites/new.html.erb:1
  app/controllers/admin/sites_controller.rb:31:in `create'
```

**Comment by ivan-kocienski-gfsc** [comment]
This seems fixed now (checking on localhost and production)
